### ISSUE TITLE
Youtube Issue

### ISSUE THREAD

**Issue by Kaelanii** [GalacticNetwork/astro#2]
Okay so I use the search bar and type youtube and watch youtube from there but if i were to like be inactive for at least two minutes it would bring me to the no internet youtube page and thats really annoying. Please lemme know if you can fix anything about this

**Comment by GalacticNetwork** [comment]
Yeah, it's more of an Ultraviolet issue, try proxying this link: https://iv.nboeck.de it's an alternative to youtube

**Comment by Kaelanii** [comment]
Okay thank you.
